Repository Kernel360/KBE5_DANMUJI_BE, pull requests merged in 2025-07, with the labels that each got.

#490 [Feature] 프로젝트 상태별 개수 조회
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/controller/code/ProjectResponseCode.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectCountResponse.java
  module-core/src/main/java/com/back2basics/project/model/Project.java
  module-core/src/main/java/com/back2basics/project/model/StatusCountProjection.java
  module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectCountResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
Labels: ✨ 기능 추가, 진효 🐰

#494 [Feature] 프로젝트 상태 별 조회 분기 처리
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
  module-core/src/main/java/com/back2basics/user/model/Role.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
  module-infra/src/main/java/com/back2basics/security/model/CustomUserDetails.java
Labels: ✨ 기능 추가, 유진 🐱

#496 [Feature] 조회 시 정렬 옵션 추가
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
Labels: ✨ 기능 추가, 유진 🐱

#500 [Feature] 단계 상태 변경 수정
  module-core/src/main/java/com/back2basics/projectstep/model/ProjectStep.java
Labels: ✨ 기능 추가, 진효 🐰

#503 [Feature] 진행률에 따른 프로젝트 상태변경
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
Labels: ✨ 기능 추가, 진효 🐰

#512 [Refactor] 첨부파일 업로드/다운로드를 presignedURL 방식으로 개선
  module-api/src/main/java/com/back2basics/domain/board/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/board/controller/code/PostResponseCode.java
  module-api/src/main/java/com/back2basics/domain/board/dto/request/PostCreateWithPresignedRequest.java
  module-api/src/main/java/com/back2basics/domain/board/dto/request/PostUpdateWithPresignedRequest.java
  module-api/src/main/java/com/back2basics/domain/board/dto/request/PresignedUploadedFileRequest.java
  module-api/src/main/resources/application.yml
  module-core/src/main/java/com/back2basics/board/file/model/File.java
  module-core/src/main/java/com/back2basics/board/file/port/in/FileDownloadUseCase.java
  module-core/src/main/java/com/back2basics/board/file/port/out/FilePresignedUrlPort.java
  module-core/src/main/java/com/back2basics/board/file/service/FileDownloadService.java
  module-core/src/main/java/com/back2basics/board/file/service/FilePresignedUrlResult.java
  module-core/src/main/java/com/back2basics/board/post/port/in/PostCreateUseCase.java
  module-core/src/main/java/com/back2basics/board/post/port/in/PostUpdateUseCase.java
  module-core/src/main/java/com/back2basics/board/post/service/PostCreateService.java
  module-core/src/main/java/com/back2basics/board/post/service/PostUpdateService.java
  module-core/src/main/java/com/back2basics/infra/exception/file/FileErrorCode.java
  module-core/src/main/java/com/back2basics/infra/s3/S3Util.java
  module-core/src/main/java/com/back2basics/infra/s3/dto/PresignedUploadCompleteInfo.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/file/FileMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/file/adapter/FileDeleteAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/file/adapter/FileSaveAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/file/adapter/S3PresignedUrlAdapter.java
  module-infra/src/main/java/com/back2basics/config/S3PresignerConfig.java
Labels: ♻️ 리팩토링, 승우 🐯

#513 Feature/restore 내용은 좀따쓸게ㅛ요 시간나면...
  module-api/src/main/java/com/back2basics/domain/board/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/board/controller/code/PostResponseCode.java
  module-core/src/main/java/com/back2basics/board/post/model/Post.java
  module-core/src/main/java/com/back2basics/board/post/port/in/PostRestoreUseCase.java
  module-core/src/main/java/com/back2basics/board/post/port/out/PostReadPort.java
  module-core/src/main/java/com/back2basics/board/post/port/out/PostRestorePort.java
  module-core/src/main/java/com/back2basics/board/post/service/PostRestoreService.java
  module-core/src/main/java/com/back2basics/board/post/service/notification/PostNotificationSender.java
  module-core/src/main/java/com/back2basics/history/model/HistoryRequestFactory.java
  module-core/src/main/java/com/back2basics/history/model/HistoryType.java
  module-core/src/main/java/com/back2basics/history/service/HistoryLogService.java
  module-core/src/main/java/com/back2basics/infra/exception/post/PostErrorCode.java
  module-core/src/main/java/com/back2basics/infra/validation/validator/PostValidator.java
  module-core/src/main/java/com/back2basics/infra/validation/validator/UserValidator.java
  module-core/src/main/java/com/back2basics/notify/model/NotificationType.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/adapter/PostReadJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/adapter/PostRestoreJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/common/entity/BaseTimeEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/notification/mention/MentionReadAdapter.java
  module-infra/src/main/java/com/back2basics/bulk/UserBulkInitializer.java
Labels: ✨ 기능 추가, 승우 🐯

#537 [Feature] 삭제 프로젝트 복구 기능 구현
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/controller/code/ProjectResponseCode.java
  module-core/src/main/java/com/back2basics/project/port/in/RestoreProjectUSeCase.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/RestoreProjectService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
Labels: ✨ 기능 추가

#538 [Deploy] 배포
  module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
  module-api/src/main/java/com/back2basics/domain/inquiry/controller/InquiryController.java
  module-api/src/main/java/com/back2basics/domain/inquiry/dto/response/ReadRecentInquiryResponse.java
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/controller/code/ProjectResponseCode.java
  module-api/src/main/java/com/back2basics/domain/projectstep/controller/ProjectStepController.java
  module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
  module-core/src/main/java/com/back2basics/assignment/model/Assignment.java
  module-core/src/main/java/com/back2basics/board/post/model/Post.java
  module-core/src/main/java/com/back2basics/company/port/in/ReadCompanyUseCase.java
  module-core/src/main/java/com/back2basics/company/port/out/ReadCompanyPort.java
  module-core/src/main/java/com/back2basics/company/service/ReadCompanyService.java
  module-core/src/main/java/com/back2basics/inquiry/model/InquiryCountsDto.java
  module-core/src/main/java/com/back2basics/inquiry/port/in/ReadInquiryUseCase.java
  module-core/src/main/java/com/back2basics/inquiry/port/out/ReadInquiryPort.java
  module-core/src/main/java/com/back2basics/inquiry/service/ReadInquiryService.java
  module-core/src/main/java/com/back2basics/inquiry/service/result/ReadRecentInquiryResult.java
  module-core/src/main/java/com/back2basics/project/model/Project.java
  module-core/src/main/java/com/back2basics/project/model/StatusCountProjection.java
  module-core/src/main/java/com/back2basics/project/port/in/RestoreProjectUSeCase.java
  module-core/src/main/java/com/back2basics/project/port/in/UpdateProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/RestoreProjectService.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
  module-core/src/main/java/com/back2basics/user/port/in/UserQueryUseCase.java
  module-core/src/main/java/com/back2basics/user/port/out/UserQueryPort.java
  module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/adapter/SaveAssignmentAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/ReadCompanyJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/InquiryEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/adapter/ReadInquiryJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/repository/UserEntityRepository.java
Labels: 🎉 배포

#539 [Feature] 프로젝트/회사 복구 관련 작업, .gitignore 수정
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
  module-api/src/main/java/com/back2basics/domain/company/controller/code/CompanyResponseCode.java
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/controller/code/ProjectResponseCode.java
  module-core/src/main/java/com/back2basics/answer/model/Answer.java
  module-core/src/main/java/com/back2basics/answer/service/CreateAnswerService.java
  module-core/src/main/java/com/back2basics/answer/service/DeleteAnswerService.java
  module-core/src/main/java/com/back2basics/answer/service/UpdateAnswerService.java
  module-core/src/main/java/com/back2basics/board/post/service/PostRestoreService.java
  module-core/src/main/java/com/back2basics/company/model/Company.java
  module-core/src/main/java/com/back2basics/company/port/in/RestoreCompanyUseCase.java
  module-core/src/main/java/com/back2basics/company/port/out/ReadCompanyPort.java
  module-core/src/main/java/com/back2basics/company/port/out/RestoreCompanyPort.java
  module-core/src/main/java/com/back2basics/company/service/RestoreCompanyService.java
  module-core/src/main/java/com/back2basics/infra/exception/company/CompanyErrorCode.java
  module-core/src/main/java/com/back2basics/infra/exception/project/ProjectErrorCode.java
  module-core/src/main/java/com/back2basics/infra/exception/user/UserErrorCode.java
  module-core/src/main/java/com/back2basics/infra/validator/CompanyValidator.java
  module-core/src/main/java/com/back2basics/infra/validator/ProjectValidator.java
  module-core/src/main/java/com/back2basics/inquiry/service/CreateInquiryService.java
  module-core/src/main/java/com/back2basics/project/model/Project.java
  module-core/src/main/java/com/back2basics/project/port/in/RestoreProjectUSeCase.java
  module-core/src/main/java/com/back2basics/project/port/in/RestoreProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/port/out/RestoreProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/RestoreProjectService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/CompanyRestoreJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/ReadCompanyJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/RestoreProjectAdapter.java
Labels: ✨ 기능 추가, ⚙️ 기타 작업, 승우 🐯

#546 [Feature] 회사 조회 시 회사별 회원 수 추가
  module-api/src/main/java/com/back2basics/domain/company/dto/response/ReadCompanyResponse.java
  module-core/src/main/java/com/back2basics/company/model/Company.java
  module-core/src/main/java/com/back2basics/company/service/result/ReadCompanyResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/dto/CompanyWithUserCountProjection.java
Labels: ✨ 기능 추가, 진효 🐰

#547 [Refactor] 삭제된 사용자를 제외하도록 쿼리 수정
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
Labels: 🐞 버그, ♻️ 리팩토링, 진효 🐰

#558 [Refactor] assigment 도메인에서 다른 도메인을 id 참조로 변경
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-core/src/main/java/com/back2basics/assignment/model/Assignment.java
  module-core/src/main/java/com/back2basics/assignment/service/result/AssignProjectListResult.java
  module-core/src/main/java/com/back2basics/assignment/service/result/AssignUserResult.java
  module-core/src/main/java/com/back2basics/assignment/service/result/ReadAssignmentResult.java
  module-core/src/main/java/com/back2basics/company/service/result/CompanySummaryResult.java
  module-core/src/main/java/com/back2basics/infra/validator/ProjectValidator.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectDetailResult.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectGetResult.java
  module-core/src/main/java/com/back2basics/user/model/User.java
  module-core/src/main/java/com/back2basics/user/service/result/UserCompanyResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/AssignmentMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
Labels: ♻️ 리팩토링, 진효 🐰

#570 [Task] api 성능 최적화를 위한 쿼리 수정, 인덱스 생성, post리팩토링
  module-api/src/main/java/com/back2basics/domain/board/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
  module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
  module-core/src/main/java/com/back2basics/board/post/port/in/PostCreateUseCase.java
  module-core/src/main/java/com/back2basics/board/post/port/in/PostUpdateUseCase.java
  module-core/src/main/java/com/back2basics/board/post/service/PostCreateService.java
  module-core/src/main/java/com/back2basics/board/post/service/PostUpdateService.java
  module-core/src/main/java/com/back2basics/board/post/service/utils/PostCreateProcessor.java
  module-core/src/main/java/com/back2basics/board/post/service/utils/PostFileService.java
  module-core/src/main/java/com/back2basics/board/post/service/utils/PostUpdateProcessor.java
  module-core/src/main/java/com/back2basics/company/model/Company.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/AssignmentEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/adapter/PostReadJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/adapter/PostSearchJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/history/HistoryReadAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/entity/UserEntity.java
  module-infra/src/main/java/com/back2basics/bulk/CommentBulkInitializer.java
Labels: 🚀 성능 개선, ♻️ 리팩토링, 승우 🐯

#574 [Feature] URL을 통해 다른 사용자의 문의사항 조회 되는 현상 수정
  module-api/src/main/java/com/back2basics/domain/inquiry/controller/InquiryController.java
  module-core/src/main/java/com/back2basics/answer/service/CreateAnswerService.java
  module-core/src/main/java/com/back2basics/infra/exception/inquiry/InquiryErrorCode.java
  module-core/src/main/java/com/back2basics/infra/validator/InquiryValidator.java
  module-core/src/main/java/com/back2basics/inquiry/port/in/ReadInquiryUseCase.java
  module-core/src/main/java/com/back2basics/inquiry/port/out/ReadInquiryPort.java
  module-core/src/main/java/com/back2basics/inquiry/service/DeleteInquiryService.java
  module-core/src/main/java/com/back2basics/inquiry/service/ReadInquiryService.java
  module-core/src/main/java/com/back2basics/inquiry/service/UpdateInquiryService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/InquiryEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/adapter/ReadInquiryJpaAdapter.java
Labels: ✨ 기능 추가, 정인 🐻

#577 [Feature] 고객사 정보 조회 기능 추가 및 체크리스트 관련 반환 값 리팩터링
  module-api/src/main/java/com/back2basics/domain/checklist/controller/ChecklistController.java
  module-api/src/main/java/com/back2basics/domain/checklist/dto/response/ChecklistDetailResponse.java
  module-api/src/main/java/com/back2basics/domain/checklist/dto/response/ChecklistInfoResponse.java
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/controller/code/ProjectResponseCode.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectClientUserResponse.java
  module-core/src/main/java/com/back2basics/checklist/port/in/ReadChecklistUseCase.java
  module-core/src/main/java/com/back2basics/checklist/port/out/ChecklistQueryPort.java
  module-core/src/main/java/com/back2basics/checklist/service/ReadApprovalService.java
  module-core/src/main/java/com/back2basics/checklist/service/ReadChecklistService.java
  module-core/src/main/java/com/back2basics/checklist/service/result/ChecklistDetailResult.java
  module-core/src/main/java/com/back2basics/checklist/service/result/ChecklistInfoResult.java
  module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectClientUserResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/checklist/adapter/ChecklistQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/checklist/repository/ChecklistEntityRepository.java
Labels: ✨ 기능 추가, ♻️ 리팩토링, 유진 🐱, 💬 SHOW

#581 [Hotfix] 문자열길이제한 커스텀어노테이션 추가, 프로젝트컨트롤러 응답메세지 추가
  module-api/src/main/java/com/back2basics/custom/CustomStringLengthCheck.java
  module-api/src/main/java/com/back2basics/custom/CustomStringLengthValidator.java
  module-api/src/main/java/com/back2basics/domain/board/dto/request/PostCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/board/dto/request/PostUpdateRequest.java
  module-api/src/main/java/com/back2basics/domain/comment/dto/request/CommentCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/comment/dto/request/CommentUpdateRequest.java
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/controller/code/ProjectResponseCode.java
Labels: ✨ 기능 추가, 승우 🐯, 💬 SHOW

#588 [Feature] 필터링 api deletedAt IS NULL인 것 만 검색되게 수정
  module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/InquirySpecifications.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/adapter/ReadInquiryJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/UserSpecifications.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
Labels: ✨ 기능 추가, 정인 🐻

#591 [hotfix] 게시글 내용 제한 글자 수 오타 수정
  module-api/src/main/java/com/back2basics/domain/board/dto/request/PostCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/board/dto/request/PostUpdateRequest.java
  module-core/src/main/java/com/back2basics/infra/validator/UserValidator.java
  module-core/src/main/java/com/back2basics/project/port/out/SearchProjectPort.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/InquirySpecifications.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/adapter/ReadInquiryJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/SearchProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/UserSpecifications.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
Labels: 승우 🐯

#598 [Feature] 체크리스트 생성/상세/조회/검증 관련 로직 및 응답 데이터 구조 개선, 회원 목록 정렬 수정
  module-api/src/main/java/com/back2basics/domain/checklist/dto/request/CreateChecklistRequest.java
  module-api/src/main/java/com/back2basics/domain/checklist/dto/request/UpdateApprovalRequest.java
  module-api/src/main/java/com/back2basics/domain/checklist/dto/response/ApprovalResponse.java
  module-api/src/main/java/com/back2basics/domain/checklist/dto/response/ChecklistDetailResponse.java
  module-core/src/main/java/com/back2basics/checklist/service/ReadApprovalService.java
  module-core/src/main/java/com/back2basics/checklist/service/result/ApprovalResult.java
  module-core/src/main/java/com/back2basics/checklist/service/result/ChecklistDetailResult.java
  module-core/src/main/java/com/back2basics/user/model/User.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/checklist/adapter/ChecklistQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/checklist/repository/ChecklistEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/repository/UserEntityRepository.java
Labels: ✨ 기능 추가, 승우 🐯

#602 [Feature] 프로젝트 상태 자동 변경 기능 구현
  module-batch/src/main/java/com/back2basics/ProjectStatusBatchScheduler.java
  module-core/src/main/java/com/back2basics/project/model/Project.java
  module-core/src/main/java/com/back2basics/project/port/in/UpdateProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
Labels: ✨ 기능 추가, 유진 🐱

#608 [Refactor] 프로젝트 생성, 수정 검증 어노테이션 추가
  module-api/src/main/java/com/back2basics/custom/CustomUserDistinctCheck.java
  module-api/src/main/java/com/back2basics/custom/CustomUserDistinctCheckValidator.java
  module-api/src/main/java/com/back2basics/custom/ManagerIncludedInUserCheck.java
  module-api/src/main/java/com/back2basics/custom/ManagerIncludedInUserCheckValidator.java
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectUpdateRequest.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/UserDistinctCheckDto.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/DeleteProjectService.java
  module-core/src/main/java/com/back2basics/project/service/RestoreProjectService.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
Labels: ✨ 기능 추가, ♻️ 리팩토링, 진효 🐰

#609 [hotfix] 프로젝트 멤버 할당 로직 오류 수정
  module-core/src/main/java/com/back2basics/assignment/model/Assignment.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
Labels: 🐞 버그, 진효 🐰, 🧙‍♂️ 해결
