Repository Kernel360/KBE5_DANMUJI_BE, pull requests merged in 2025-05, with the labels that each got.

#6 refactor: profiles 별 나눈 .yml들을 .yml 파일 하나로 통합 #4
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-temp.yml
  module-api/src/main/resources/application.yml
Labels: 📁 파일 수정, 승우 🐯

#7 refactor: Application 클래스 제거, 의존성/스캔 범위 정리, 오타 수정
  module-api/build.gradle
  module-api/src/main/java/back2basics/moduleapi/ModuleApiApplication.java
  module-api/src/main/resources/application.yml
  module-common/src/main/java/back2basics/modulecommon/ModuleCommonApplication.java
  module-domain/src/main/java/back2basics/moduledomain/ModuleDomainApplication.java
  module-infra/src/main/java/back2basics/moduleinfra/ModuleInfraApplication.java
  module-service/src/main/java/back2basics/moduleservice/ModuleServiceApplication.java
Labels: 🙋🏻 리뷰 요청, 📦 의존성 변경, ⚙️ 기타 작업, ♻️ 리팩토링, 유진 🐱

#12 chore: mysql 의존성 추가 (#4)
  module-application/build.gradle
Labels: 📄 문서, ⚙️ 기타 작업, 승우 🐯

#14 feat: 공통 에러응답 및 글로벌 핸들러 생성 (#3)
  build.gradle
  module-adapter-web/src/main/java/com/back2basics/controller/deleteMe.txt
  module-adapter-web/src/main/java/com/back2basics/global/error/ErrorCode.java
  module-adapter-web/src/main/java/com/back2basics/global/error/ErrorResponse.java
  module-adapter-web/src/main/java/com/back2basics/global/exception/CustomException.java
  module-adapter-web/src/main/java/com/back2basics/global/exception/GlobalExceptionHandler.java
Labels: ✨ 기능 추가, 🙋🏻 리뷰 요청, 승우 🐯

#23 [Feature] Post CRUD 구현 todo : 세부사항 고도화
  build.gradle
  module-application/build.gradle
  module-application/src/main/java/com/back2basics/DanmujiApplication.java
  module-common/build.gradle
  module-common/src/main/java/com/back2basics/response/ResponseCode.java
  module-common/src/main/java/com/back2basics/response/global/error/CommonErrorCode.java
  module-common/src/main/java/com/back2basics/response/global/error/ErrorCode.java
  module-common/src/main/java/com/back2basics/response/global/error/ErrorResponse.java
  module-common/src/main/java/com/back2basics/response/global/error/exception/CustomException.java
  module-common/src/main/java/com/back2basics/response/global/result/ResponseCode.java
  module-common/src/main/java/com/back2basics/response/global/result/ResultResponse.java
  module-common/src/main/java/com/back2basics/response/post/PostResponseCode.java
  module-core/build.gradle
  module-core/src/main/java/com/back2basics/model/deleteMe.txt
  module-core/src/main/java/com/back2basics/model/post/Post.java
  module-core/src/main/java/com/back2basics/port/in/deleteMe.txt
  module-core/src/main/java/com/back2basics/port/in/post/CreatePostUseCase.java
  module-core/src/main/java/com/back2basics/port/in/post/DeletePostUseCase.java
  module-core/src/main/java/com/back2basics/port/in/post/GetPostUseCase.java
  module-core/src/main/java/com/back2basics/port/in/post/UpdatePostUseCase.java
  module-core/src/main/java/com/back2basics/port/out/deleteMe.txt
  module-core/src/main/java/com/back2basics/port/out/post/PostRepositoryPort.java
  module-core/src/main/java/com/back2basics/service/deleteMe.txt
  module-core/src/main/java/com/back2basics/service/post/PostServiceImpl.java
  module-core/src/main/java/com/back2basics/service/post/dto/PostCreateCommand.java
  module-core/src/main/java/com/back2basics/service/post/dto/PostResponseDto.java
  module-core/src/main/java/com/back2basics/service/post/dto/PostUpdateCommand.java
  module-core/src/main/java/com/back2basics/service/post/exception/PostErrorCode.java
  module-core/src/main/java/com/back2basics/service/post/exception/PostException.java
  module-jpa/src/main/java/com/back2basics/common/entity/common/BaseTimeEntity.java
  module-jpa/src/main/java/com/back2basics/post/adapter/out/PostJpaAdapter.java
  module-jpa/src/main/java/com/back2basics/post/entity/PostEntity.java
  module-jpa/src/main/java/com/back2basics/post/mapper/PostMapper.java
  module-jpa/src/main/java/com/back2basics/post/repository/PostEntityRepository.java
  module-web/src/main/java/com/back2basics/global/handler/GlobalExceptionHandler.java
  module-web/src/main/java/com/back2basics/post/controller/PostController.java
Labels: ✨ 기능 추가, 🙋🏻 리뷰 요청, ♻️ 리팩토링, 승우 🐯

#24 [Refactor] 디렉토리 수정
  module-jpa/src/main/java/com/back2basics/common/entity/BaseTimeEntity.java
  module-jpa/src/main/java/com/back2basics/post/entity/PostEntity.java
Labels: 🙋🏻 리뷰 요청, 📁 파일 수정, 승우 🐯

#30 [Fix] 코멘트 이슈 반영
  module-core/src/main/java/com/back2basics/infra/custom/CustomNotBlankValidator.java
  module-core/src/main/java/com/back2basics/infra/custom/CustomTitleNotBlank.java
  module-core/src/main/java/com/back2basics/infra/validation/PostValidator.java
  module-core/src/main/java/com/back2basics/model/post/Post.java
  module-core/src/main/java/com/back2basics/port/in/post/DeletePostUseCase.java
  module-core/src/main/java/com/back2basics/port/in/post/GetPostUseCase.java
  module-core/src/main/java/com/back2basics/port/out/post/PostRepositoryPort.java
  module-core/src/main/java/com/back2basics/service/post/PostServiceImpl.java
  module-core/src/main/java/com/back2basics/service/post/dto/PostResponseDto.java
  module-core/src/main/java/com/back2basics/service/post/dto/PostUpdateCommand.java
  module-core/src/main/java/com/back2basics/service/post/exception/PostErrorCode.java
  module-jpa/src/main/java/com/back2basics/post/entity/PostEntity.java
  module-jpa/src/main/java/com/back2basics/post/mapper/PostMapper.java
  module-jpa/src/main/java/com/back2basics/post/repository/PostEntityRepository.java
  module-web/src/main/java/com/back2basics/post/controller/PostController.java
Labels: ✨ 기능 추가, 🙋🏻 리뷰 요청, 📁 파일 수정, ♻️ 리팩토링

#32 feature: 공통 응답 코드 개선
  module-application/src/main/resources/application.yml
  module-common/src/main/java/com/back2basics/response/global/code/BaseCode.java
  module-common/src/main/java/com/back2basics/response/global/code/CommonErrorCode.java
  module-common/src/main/java/com/back2basics/response/global/code/ErrorCode.java
  module-common/src/main/java/com/back2basics/response/global/code/ResponseCode.java
  module-common/src/main/java/com/back2basics/response/global/error/CommonErrorCode.java
  module-common/src/main/java/com/back2basics/response/global/error/CustomException.java
  module-common/src/main/java/com/back2basics/response/global/error/ErrorCode.java
  module-common/src/main/java/com/back2basics/response/global/error/ErrorResponse.java
  module-common/src/main/java/com/back2basics/response/global/error/exception/CustomException.java
  module-common/src/main/java/com/back2basics/response/global/result/ApiResponse.java
  module-common/src/main/java/com/back2basics/response/global/result/ResponseCode.java
  module-common/src/main/java/com/back2basics/response/global/result/ResultResponse.java
  module-common/src/main/java/com/back2basics/response/post/PostResponseCode.java
  module-core/build.gradle
  module-core/src/main/java/com/back2basics/infra/validation/PostValidator.java
  module-core/src/main/java/com/back2basics/model/post/Post.java
  module-core/src/main/java/com/back2basics/service/post/PostServiceImpl.java
  module-core/src/main/java/com/back2basics/service/post/exception/PostErrorCode.java
  module-core/src/main/java/com/back2basics/service/post/exception/PostException.java
  module-core/src/main/java/com/back2basics/service/post/response/PostResponseCode.java
  module-web/src/main/java/com/back2basics/global/handler/GlobalExceptionHandler.java
  module-web/src/main/java/com/back2basics/post/controller/PostController.java
Labels: ✅ 리뷰 승인, ⚙️ 기타 작업, ♻️ 리팩토링, 유진 🐱

#49 [Feature] User CRUD 구현
  module-common/src/main/java/com/back2basics/util/PasswordGenerator.java
  module-core/src/main/java/com/back2basics/infra/user/validation/UserValidator.java
  module-core/src/main/java/com/back2basics/model/user/Role.java
  module-core/src/main/java/com/back2basics/model/user/User.java
  module-core/src/main/java/com/back2basics/port/in/user/CreateUserUseCase.java
  module-core/src/main/java/com/back2basics/port/in/user/DeleteUserUseCase.java
  module-core/src/main/java/com/back2basics/port/in/user/GetUserUseCase.java
  module-core/src/main/java/com/back2basics/port/in/user/UpdateUserUseCase.java
  module-core/src/main/java/com/back2basics/port/out/user/UserRepositoryPort.java
  module-core/src/main/java/com/back2basics/service/user/UserServiceImpl.java
  module-core/src/main/java/com/back2basics/service/user/command/UserCreateCommand.java
  module-core/src/main/java/com/back2basics/service/user/command/UserUpdateCommand.java
  module-core/src/main/java/com/back2basics/service/user/exception/UserErrorCode.java
  module-core/src/main/java/com/back2basics/service/user/exception/UserException.java
  module-core/src/main/java/com/back2basics/service/user/response/UserResponseCode.java
  module-core/src/main/java/com/back2basics/service/user/result/UserCreateResult.java
  module-core/src/main/java/com/back2basics/service/user/result/UserInfoResult.java
  module-jpa/src/main/java/com/back2basics/common/entity/BaseTimeEntity.java
  module-jpa/src/main/java/com/back2basics/user/adapter/out/UserJpaAdapter.java
  module-jpa/src/main/java/com/back2basics/user/entity/UserEntity.java
  module-jpa/src/main/java/com/back2basics/user/mapper/UserMapper.java
  module-jpa/src/main/java/com/back2basics/user/repository/UserEntityRepository.java
  module-web/src/main/java/com/back2basics/admin/controller/AdminController.java
  module-web/src/main/java/com/back2basics/admin/dto/request/UserCreateRequest.java
  module-web/src/main/java/com/back2basics/admin/dto/request/UserUpdateRequest.java
  module-web/src/main/java/com/back2basics/admin/dto/response/UserCreateResponse.java
  module-web/src/main/java/com/back2basics/admin/dto/response/UserInfoResponse.java
  module-web/src/main/java/com/back2basics/user/controller/UserController.java
Labels: ✨ 기능 추가, ✅ 리뷰 승인, 유진 🐱

#45 [Feature] 회사 CRUD 기능 구현
  module-core/src/main/java/com/back2basics/infra/validation/CompanyValidator.java
  module-core/src/main/java/com/back2basics/model/company/Company.java
  module-core/src/main/java/com/back2basics/model/company/CompanyType.java
  module-core/src/main/java/com/back2basics/port/in/company/CreateCompanyUseCase.java
  module-core/src/main/java/com/back2basics/port/in/company/DeleteCompanyUseCase.java
  module-core/src/main/java/com/back2basics/port/in/company/GetAllCompaniesUseCase.java
  module-core/src/main/java/com/back2basics/port/in/company/GetCompanyByIdUseCase.java
  module-core/src/main/java/com/back2basics/port/in/company/UpdateCompanyUseCase.java
  module-core/src/main/java/com/back2basics/port/out/company/CompanyRepositoryPort.java
  module-core/src/main/java/com/back2basics/service/company/CompanyServiceImpl.java
  module-core/src/main/java/com/back2basics/service/company/dto/CompanyCreateCommand.java
  module-core/src/main/java/com/back2basics/service/company/dto/CompanyResponseDto.java
  module-core/src/main/java/com/back2basics/service/company/dto/CompanyUpdateCommand.java
  module-core/src/main/java/com/back2basics/service/company/exception/CompanyErrorCode.java
  module-core/src/main/java/com/back2basics/service/company/exception/CompanyException.java
  module-jpa/src/main/java/com/back2basics/company/adapter/out/CompanyJpaAdapter.java
  module-jpa/src/main/java/com/back2basics/company/entity/CompanyEntity.java
  module-jpa/src/main/java/com/back2basics/company/mapper/CompanyMapper.java
  module-jpa/src/main/java/com/back2basics/company/repository/CompanyEntityRepository.java
  module-web/src/main/java/com/back2basics/company/controller/CompanyController.java
  module-web/src/main/java/com/back2basics/company/response/CompanyResponseCode.java
Labels: ✨ 기능 추가, 🙋🏻 리뷰 요청, 📝 현재 리뷰 중, 정인 🐻

#66 [Feature] User CRUD 개선
  module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
  module-api/src/main/java/com/back2basics/domain/user/controller/UserController.java
  module-api/src/main/java/com/back2basics/domain/user/controller/code/UserResponseCode.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/ChangePasswordRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/ResetPasswordRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/UserCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/UserUpdateRequest.java
  module-api/src/main/resources/application-test.yml
  module-api/src/main/resources/application.yml
  module-core/src/main/java/com/back2basics/infra/exception/user/UserErrorCode.java
  module-core/src/main/java/com/back2basics/infra/validation/validator/UserValidator.java
  module-core/src/main/java/com/back2basics/port/out/mail/MailSenderPort.java
  module-core/src/main/java/com/back2basics/user/model/User.java
  module-core/src/main/java/com/back2basics/user/port/in/ChangePasswordUseCase.java
  module-core/src/main/java/com/back2basics/user/port/in/CreateUserUseCase.java
  module-core/src/main/java/com/back2basics/user/port/in/DeleteUserUseCase.java
  module-core/src/main/java/com/back2basics/user/port/in/GetUserUseCase.java
  module-core/src/main/java/com/back2basics/user/port/in/ResetPasswordUseCase.java
  module-core/src/main/java/com/back2basics/user/port/in/UpdateUserUseCase.java
  module-core/src/main/java/com/back2basics/user/port/in/command/ChangePasswordCommand.java
  module-core/src/main/java/com/back2basics/user/port/in/command/ResetPasswordCommand.java
  module-core/src/main/java/com/back2basics/user/port/in/command/UserUpdateCommand.java
  module-core/src/main/java/com/back2basics/user/port/out/UserRepositoryPort.java
  module-core/src/main/java/com/back2basics/user/service/CreateUserService.java
  module-core/src/main/java/com/back2basics/user/service/DeleteUserService.java
  module-core/src/main/java/com/back2basics/user/service/GetUserService.java
  module-core/src/main/java/com/back2basics/user/service/UpdateUserService.java
  module-core/src/main/java/com/back2basics/user/service/UserServiceImpl.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/entity/UserEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
Labels: ✨ 기능 추가, 📁 파일 수정, ♻️ 리팩토링, 유진 🐱

#76 [Test] 게시글 기본CRUD 테스트 코드
  module-api/src/test/java/com/back2basics/comment/model/CommentModelTest.java
  module-api/src/test/java/com/back2basics/comment/service/CommentServiceImplTest.java
  module-api/src/test/java/com/back2basics/comment/validator/CommentValidatorTest.java
  module-api/src/test/java/com/back2basics/post/adapter/PostPersistenceAdapterTest.java
  module-api/src/test/java/com/back2basics/post/model/PostModelTest.java
  module-api/src/test/java/com/back2basics/post/service/PostServiceImplTest.java
  module-api/src/test/java/com/back2basics/post/validator/PostValidatorTest.java
Labels: 💊 테스트 코드, 승우 🐯

#84 [Fix] Company 조회 시 email, tel이 null값으로 나오던 현상 수정
  module-core/src/main/java/com/back2basics/company/service/result/CompanyInfoResult.java
Labels: 🐞 버그, ✨ 기능 추가, 정인 🐻, 💬 SHOW

#87 [Fix] pr리뷰 관련 project 수정
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectUpdateRequest.java
  module-core/src/main/java/com/back2basics/infra/validation/validator/ProjectValidator.java
  module-core/src/main/java/com/back2basics/project/model/Project.java
  module-core/src/main/java/com/back2basics/project/port/in/GetProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/in/UpdateProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/in/command/ProjectResponseDto.java
  module-core/src/main/java/com/back2basics/project/port/out/ProjectRepositoryPort.java
  module-core/src/main/java/com/back2basics/project/service/ProjectServiceImpl.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectUpdateResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/out/ProjectJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/repository/ProjectEntityRepository.java
Labels: 🐞 버그, ❌ 삭제, ♻️ 리팩토링, 진효 🐰, 🚢 SHIP

#90 [Refactor] 변경된 프로젝트 구조에 맞게 수정
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/port/out/SaveProjectPort.java
  module-core/src/main/java/com/back2basics/project/port/out/UpdateProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/DeleteProjectService.java
  module-core/src/main/java/com/back2basics/project/service/ProjectServiceImpl.java
  module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/SaveProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/UpdateProjectAdapter.java
Labels: ♻️ 리팩토링, 진효 🐰, 🚢 SHIP

#100 [Refactor] 불필요 클래스 삭제 및 리턴타입 변경
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectCreateResponse.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectUpdateResponse.java
  module-core/src/main/java/com/back2basics/project/port/in/UpdateProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/service/ProjectServiceImpl.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectCreateResult.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectUpdateResult.java
Labels: ❌ 삭제, ♻️ 리팩토링, 진효 🐰

#101 [Test] 페이징 테스트코드 추가
  module-api/build.gradle
  module-api/src/test/java/com/back2basics/post/adapter/PostReadJpaAdapterTest.java
  module-api/src/test/java/com/back2basics/post/service/PostReadServiceTest.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostReadJpaAdapter.java
Labels: ✨ 기능 추가, 💊 테스트 코드, 승우 🐯, 💬 SHOW

#109 [Docs] post 컨트롤러에 swagger ui 적용 및 버그/오타 수정
  module-api/build.gradle
  module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/post/docs/PostApiDocs.java
  module-api/src/main/java/com/back2basics/domain/post/docs/PostDocsResult.java
  module-api/src/main/java/com/back2basics/global/controller/FaviconController.java
  module-api/src/main/resources/application.yml
Labels: 📄 문서, ✨ 기능 추가, 📁 파일 수정, 승우 🐯, 💬 SHOW

#110 [Refactor] Company 수정 기능 분리 작업
  module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
  module-api/src/main/java/com/back2basics/domain/company/dto/request/UpdateCompanyRequest.java
  module-core/src/main/java/com/back2basics/company/port/in/command/UpdateCompanyCommand.java
  module-core/src/main/java/com/back2basics/company/port/out/CompanyRepositoryPort.java
  module-core/src/main/java/com/back2basics/company/port/out/UpdateCompanyPort.java
  module-core/src/main/java/com/back2basics/company/service/CompanyServiceImpl.java
  module-core/src/main/java/com/back2basics/company/service/UpdateCompanyService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/UpdateCompanyJpaAdapter.java
Labels: ♻️ 리팩토링, 정인 🐻, 💬 SHOW

#111 [Refactor] Company 삭제 기능 분리 작업
  module-core/src/main/java/com/back2basics/company/port/out/DeleteCompanyPort.java
  module-core/src/main/java/com/back2basics/company/service/DeleteCompanyService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/DeleteCompanyJpaAdapter.java
Labels: ♻️ 리팩토링, 정인 🐻, 💬 SHOW

#118 [Docs] 클래스 위치 변경 및 삭제(#88)
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/SaveProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/UpdateProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/out/ProjectJpaAdapter.java
Labels: ❌ 삭제, 📁 파일 수정, 진효 🐰

#124 [Fix] 댓글 command 디렉토리 위치 실수 수정 (#122)
  module-api/src/main/java/com/back2basics/domain/comment/dto/request/CommentCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/comment/dto/request/CommentDeleteRequest.java
  module-api/src/main/java/com/back2basics/domain/comment/dto/request/CommentUpdateRequest.java
  module-api/src/test/java/com/back2basics/comment/model/CommentTest.java
  module-api/src/test/java/com/back2basics/comment/service/CommentCreateServiceTest.java
  module-api/src/test/java/com/back2basics/comment/service/CommentUpdateServiceTest.java
  module-core/src/main/java/com/back2basics/comment/model/Comment.java
  module-core/src/main/java/com/back2basics/comment/port/in/CommentCreateUseCase.java
  module-core/src/main/java/com/back2basics/comment/port/in/CommentUpdateUseCase.java
  module-core/src/main/java/com/back2basics/comment/port/in/command/CommentCreateCommand.java
  module-core/src/main/java/com/back2basics/comment/port/in/command/CommentDeleteCommand.java
  module-core/src/main/java/com/back2basics/comment/port/in/command/CommentUpdateCommand.java
  module-core/src/main/java/com/back2basics/comment/service/CommentCreateService.java
  module-core/src/main/java/com/back2basics/comment/service/CommentModelRelationHelper.java
  module-core/src/main/java/com/back2basics/comment/service/CommentUpdateService.java
Labels: 📁 파일 수정, 승우 🐯, 🚢 SHIP

#127 [Docs] 댓글 swagger ui 적용 및 게시글 swagger 응답 형식 수정
  module-api/src/main/java/com/back2basics/domain/comment/controller/CommentController.java
  module-api/src/main/java/com/back2basics/domain/comment/swagger/CommentApiDocs.java
  module-api/src/main/java/com/back2basics/domain/comment/swagger/CommentDocsResult.java
  module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostApiDocs.java
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostDocsResult.java
Labels: 📄 문서, 📁 파일 수정, ♻️ 리팩토링, 승우 🐯, 🚢 SHIP
