Repository Kernel360/KBE5_DANMUJI_BE, pull requests merged in 2025-06, with the labels that each got.

#136 [Refactor] 게시글,댓글 연관관계 수정 (양방향->단방향)
  module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/post/dto/response/PostListReadResponse.java
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostApiDocs.java
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostDocsResult.java
  module-api/src/test/java/com/back2basics/comment/adapter/CommentCreateJpaAdapterTest.java
  module-api/src/test/java/com/back2basics/comment/adapter/CommentDeleteJpaAdapterTest.java
  module-api/src/test/java/com/back2basics/comment/adapter/CommentReadJpaAdapterTest.java
  module-api/src/test/java/com/back2basics/comment/adapter/CommentUpdateJpaAdapterTest.java
  module-api/src/test/java/com/back2basics/comment/model/CommentTest.java
  module-api/src/test/java/com/back2basics/comment/service/CommentCreateServiceTest.java
  module-api/src/test/java/com/back2basics/post/adapter/PostReadJpaAdapterTest.java
  module-api/src/test/java/com/back2basics/post/service/PostReadServiceTest.java
  module-core/src/main/java/com/back2basics/comment/model/Comment.java
  module-core/src/main/java/com/back2basics/comment/service/CommentCreateService.java
  module-core/src/main/java/com/back2basics/comment/service/CommentModelRelationHelper.java
  module-core/src/main/java/com/back2basics/post/model/Post.java
  module-core/src/main/java/com/back2basics/post/port/in/PostReadUseCase.java
  module-core/src/main/java/com/back2basics/post/port/in/PostSearchUseCase.java
  module-core/src/main/java/com/back2basics/post/service/PostReadService.java
  module-core/src/main/java/com/back2basics/post/service/PostSearchService.java
  module-core/src/main/java/com/back2basics/post/service/result/PostListReadResult.java
  module-core/src/main/java/com/back2basics/user/model/User.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/CommentEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/CommentMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/adapter/CommentCreateJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/adapter/CommentDeleteJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/adapter/CommentUpdateJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/utils/CommentDeleteHelper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/utils/CommentRelationHelper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/utils/CommentUpdateHelper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostReadJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostSearchJpaAdapter.java
Labels: 💊 테스트 코드, ♻️ 리팩토링, 승우 🐯, 🚢 SHIP

#140 [Feature] 회원 - 회사 연관관계 매핑
  module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/UserCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/UserUpdateRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserCreateResponse.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserInfoResponse.java
  module-core/src/main/java/com/back2basics/user/model/User.java
  module-core/src/main/java/com/back2basics/user/port/in/command/UserCreateCommand.java
  module-core/src/main/java/com/back2basics/user/port/in/command/UserUpdateCommand.java
  module-core/src/main/java/com/back2basics/user/service/CreateUserService.java
  module-core/src/main/java/com/back2basics/user/service/GetUserService.java
  module-core/src/main/java/com/back2basics/user/service/UpdateUserService.java
  module-core/src/main/java/com/back2basics/user/service/result/UserCreateResult.java
  module-core/src/main/java/com/back2basics/user/service/result/UserInfoResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/entity/UserEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
Labels: ✨ 기능 추가, ✅ 리뷰 승인, 정인 🐻

#150 [Feature] 회사 수정 HTTP 메서드 PATCH에서 PUT으로 수정
  module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
  module-core/src/main/java/com/back2basics/company/model/Company.java
Labels: ✨ 기능 추가, 정인 🐻, 💬 SHOW

#165 [Feature] 프로젝트 단계 삭제 구현
  module-api/src/main/java/com/back2basics/domain/projectstep/controller/ProjectStepController.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/projectstep/model/ProjectStep.java
  module-core/src/main/java/com/back2basics/projectstep/port/in/DeleteProjectStepUseCase.java
  module-core/src/main/java/com/back2basics/projectstep/service/CreateProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/DeleteProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/result/ReadProjectStepResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/adapter/ReadProjectStepAdapter.java
Labels: ✨ 기능 추가, 🚧 작업 중, 진효 🐰

#133 [Feature] 로그인/로그아웃 기능 구현
  module-api/build.gradle
  module-api/src/main/java/com/back2basics/domain/auth/AuthService.java
  module-api/src/main/java/com/back2basics/domain/auth/controller/AuthController.java
  module-api/src/main/java/com/back2basics/domain/auth/dto/LoginRequest.java
  module-api/src/main/java/com/back2basics/domain/auth/dto/TokenPair.java
  module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
  module-api/src/main/java/com/back2basics/global/security/config/SecurityConfig.java
  module-api/src/main/java/com/back2basics/global/security/exception/CustomBadCredentialsException.java
  module-api/src/main/java/com/back2basics/global/security/filter/JwtAuthorizationFilter.java
  module-api/src/main/resources/application-test.yml
  module-api/src/main/resources/application.yml
  module-api/src/test/java/com/back2basics/security/LoginFailTest.java
  module-api/src/test/java/com/back2basics/security/LoginSuccessTest.java
  module-api/src/test/java/com/back2basics/security/LogoutTest.java
  module-api/src/test/java/com/back2basics/security/ReissueFailTest.java
  module-api/src/test/java/com/back2basics/security/ReissueSuccessTest.java
  module-common/src/main/java/com/back2basics/global/response/util/ResponseUtil.java
  module-core/build.gradle
  module-core/src/main/java/com/back2basics/user/model/User.java
  module-core/src/main/java/com/back2basics/user/port/in/UserQueryUseCase.java
  module-core/src/main/java/com/back2basics/user/port/out/UserRepositoryPort.java
  module-core/src/main/java/com/back2basics/user/service/ChangePasswordService.java
  module-core/src/main/java/com/back2basics/user/service/CreateUserService.java
  module-core/src/main/java/com/back2basics/user/service/ResetPasswordService.java
  module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
  module-infra/build.gradle
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/entity/UserEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/repository/UserEntityRepository.java
  module-infra/src/main/java/com/back2basics/config/RedisConfig.java
  module-infra/src/main/java/com/back2basics/security/code/AuthErrorCode.java
  module-infra/src/main/java/com/back2basics/security/code/AuthResponseCode.java
  module-infra/src/main/java/com/back2basics/security/code/RedisErrorCode.java
  module-infra/src/main/java/com/back2basics/security/exception/CustomRedisConnectionException.java
  module-infra/src/main/java/com/back2basics/security/exception/InvalidTokenException.java
  module-infra/src/main/java/com/back2basics/security/jwt/JwtTokenProvider.java
  module-infra/src/main/java/com/back2basics/security/model/CustomUserDetails.java
  module-infra/src/main/java/com/back2basics/security/service/CustomUserDetailsService.java
  module-infra/src/main/java/com/back2basics/util/CookieUtil.java
  module-infra/src/main/java/com/back2basics/util/RedisUtil.java
Labels: ✨ 기능 추가, ✅ 리뷰 승인, 💊 테스트 코드, 📦 의존성 변경, 유진 🐱

#167 [Fix] 에러메세지 수정 및 http 메서드 변경
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/projectstep/controller/ProjectStepController.java
  module-api/src/main/java/com/back2basics/domain/projectstep/controller/code/ProjectStepResponseCode.java
  module-core/src/main/java/com/back2basics/infra/exception/projectstep/ProjectStepException.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/adapter/ReadProjectStepAdapter.java
Labels: 📁 파일 수정, 진효 🐰

#169 [FIX] user - company 매핑 수정 (#168)
  module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserCreateResponse.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserInfoResponse.java
  module-api/src/test/java/com/back2basics/security/LoginFailTest.java
  module-api/src/test/java/com/back2basics/security/LoginSuccessTest.java
  module-api/src/test/java/com/back2basics/security/LogoutTest.java
  module-api/src/test/java/com/back2basics/security/ReissueFailTest.java
  module-api/src/test/java/com/back2basics/security/ReissueSuccessTest.java
  module-core/src/main/java/com/back2basics/user/model/User.java
  module-core/src/main/java/com/back2basics/user/service/CreateUserService.java
  module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
  module-core/src/main/java/com/back2basics/user/service/result/UserCreateResult.java
  module-core/src/main/java/com/back2basics/user/service/result/UserInfoResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
Labels: ❌ 삭제, ♻️ 리팩토링, 유진 🐱, 🚢 SHIP

#173 [Feature] user 개발사 담당자, 고객사 담당자 필드 추가 및 조회 시 생성일자, 수정일자 포함
  module-api/src/main/java/com/back2basics/domain/user/dto/request/UserCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserInfoResponse.java
  module-core/src/main/java/com/back2basics/user/model/User.java
  module-core/src/main/java/com/back2basics/user/model/UserType.java
  module-core/src/main/java/com/back2basics/user/port/in/command/UserCreateCommand.java
  module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
  module-core/src/main/java/com/back2basics/user/service/result/UserInfoResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/entity/UserEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
Labels: ✨ 기능 추가, 유진 🐱, 🚢 SHIP

#176 [Feature] Swagger 사용을 위해 SecurityConfig 수정
  module-api/src/main/java/com/back2basics/global/security/config/SecurityConfig.java
Labels: ✨ 기능 추가, 유진 🐱, 🚢 SHIP

#166 [Feature] 회사 검색 기능 세부 수정
  module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
  module-core/src/main/java/com/back2basics/company/port/in/ReadCompanyUseCase.java
  module-core/src/main/java/com/back2basics/company/port/out/ReadCompanyPort.java
  module-core/src/main/java/com/back2basics/company/service/ReadCompanyService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/ReadCompanyJpaAdapter.java
Labels: ✨ 기능 추가, 정인 🐻, 🚢 SHIP

#196 [Refactor] principal -> CustomUserDetails 사용
  module-api/src/main/java/com/back2basics/domain/user/controller/UserController.java
  module-core/src/main/java/com/back2basics/user/port/in/ChangePasswordUseCase.java
  module-core/src/main/java/com/back2basics/user/port/in/UserQueryUseCase.java
  module-core/src/main/java/com/back2basics/user/service/ChangePasswordService.java
  module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
Labels: ✨ 기능 추가, ♻️ 리팩토링, 유진 🐱, 🚢 SHIP

#203 [Feature] Company Swagger API 추가
  module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
  module-api/src/main/java/com/back2basics/domain/company/swagger/CompanyApiDocs.java
  module-api/src/main/java/com/back2basics/domain/company/swagger/CompanyDocsResult.java
  module-api/src/main/java/com/back2basics/global/handler/GlobalExceptionHandler.java
Labels: ✨ 기능 추가, 정인 🐻, 💬 SHOW

#208 [Docs] Swagger 수정
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostDocsResult.java
  module-api/src/main/java/com/back2basics/domain/question/swagger/QuestionDocsResult.java
  module-infra/src/main/java/com/back2basics/config/SwaggerConfig.java
Labels: 📄 문서, 승우 🐯, 💬 SHOW

#209 [Feature] project_user create 구현
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/CreateProjectUserRequest.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectCreateRequest.java
  module-core/src/main/java/com/back2basics/company/model/CompanyType.java
  module-core/src/main/java/com/back2basics/project/port/in/command/ProjectCreateCommand.java
  module-core/src/main/java/com/back2basics/project/port/out/SaveProjectUserPort.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/projectuser/model/ProjectUser.java
  module-core/src/main/java/com/back2basics/user/model/UserType.java
  module-core/src/main/java/com/back2basics/userByProject/model/ProjectRole.java
  module-core/src/main/java/com/back2basics/userByProject/model/UserByProject.java
  module-core/src/main/java/com/back2basics/userByProject/port/in/CreateUserProjectUseCase.java
  module-core/src/main/java/com/back2basics/userByProject/port/in/UpdateRoleUseCase.java
  module-core/src/main/java/com/back2basics/userByProject/port/in/command/CreateUserProjectCommand.java
  module-core/src/main/java/com/back2basics/userByProject/port/out/SaveUserProjectPort.java
  module-core/src/main/java/com/back2basics/userByProject/service/CreateUserProjectService.java
  module-core/src/main/java/com/back2basics/userByProject/service/UpdateRoleService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/UserByProject/adapter/SaveUserProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/ProjectUserEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/ProjectUserEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/ProjectUserMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/adapter/SaveProjectUserAdapter.java
Labels: ✨ 기능 추가, 진효 🐰, 🚢 SHIP

#219 [Fix] 누락된 swagger 응답 및 자잘한 버그 수정
  module-api/src/main/java/com/back2basics/domain/answer/controller/AnswerController.java
  module-api/src/main/java/com/back2basics/domain/answer/swagger/AnswerDocsResult.java
  module-api/src/main/java/com/back2basics/domain/comment/controller/CommentController.java
  module-api/src/main/java/com/back2basics/domain/comment/swagger/CommentDocsResult.java
  module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/question/dto/response/QuestionResponse.java
  module-api/src/main/java/com/back2basics/domain/question/swagger/QuestionDocsResult.java
  module-core/src/main/java/com/back2basics/answer/model/Answer.java
  module-core/src/main/java/com/back2basics/post/model/Post.java
  module-core/src/main/java/com/back2basics/question/model/Question.java
  module-core/src/main/java/com/back2basics/question/service/result/QuestionResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/question/QuestionMapper.java
Labels: 📄 문서, ♻️ 리팩토링, 승우 🐯, 🚢 SHIP

#222 [Feature] user api 수정
  module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserInfoResponse.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserSimpleResponse.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserSummaryResponse.java
  module-core/src/main/java/com/back2basics/user/port/in/UserQueryUseCase.java
  module-core/src/main/java/com/back2basics/user/port/out/UserQueryPort.java
  module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
  module-core/src/main/java/com/back2basics/user/service/result/UserInfoResult.java
  module-core/src/main/java/com/back2basics/user/service/result/UserSimpleResult.java
  module-core/src/main/java/com/back2basics/user/service/result/UserSummaryResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
Labels: ✨ 기능 추가, ♻️ 리팩토링, 유진 🐱, 🚢 SHIP

#224 [Fix] 유저 응답 객체 수정, swagger 응답 수정
  module-api/src/main/java/com/back2basics/domain/answer/dto/response/AnswerResponse.java
  module-api/src/main/java/com/back2basics/domain/comment/dto/response/CommentResponse.java
  module-api/src/main/java/com/back2basics/domain/comment/swagger/CommentDocsResult.java
  module-api/src/main/java/com/back2basics/domain/post/dto/response/PostReadResponse.java
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostDocsResult.java
  module-api/src/main/java/com/back2basics/domain/question/dto/response/QuestionResponse.java
  module-api/src/main/java/com/back2basics/domain/question/swagger/QuestionDocsResult.java
  module-core/src/main/java/com/back2basics/answer/service/result/AnswerReadResult.java
  module-core/src/main/java/com/back2basics/comment/service/result/CommentReadResult.java
  module-core/src/main/java/com/back2basics/post/service/result/PostReadResult.java
  module-core/src/main/java/com/back2basics/question/service/result/QuestionResult.java
Labels: 📄 문서, ♻️ 리팩토링, 승우 🐯, 🚢 SHIP

#237 [Feature] 회사 직원 조회 API
  module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
  module-core/src/main/java/com/back2basics/company/port/in/ReadCompanyUseCase.java
  module-core/src/main/java/com/back2basics/company/service/ReadCompanyService.java
  module-core/src/main/java/com/back2basics/infra/validation/validator/CompanyValidator.java
  module-core/src/main/java/com/back2basics/user/port/out/UserQueryPort.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/entity/UserEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/repository/UserEntityRepository.java
Labels: ✨ 기능 추가, ♻️ 리팩토링, 유진 🐱, 🚢 SHIP

#242 refactor: 정적 팩토리 메서드 규칙에 따라 리팩토링
  module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
  module-core/src/main/java/com/back2basics/user/service/result/UserInfoResult.java
  module-core/src/main/java/com/back2basics/user/service/result/UserSimpleResult.java
Labels: ♻️ 리팩토링, 유진 🐱, 💬 SHOW

#243 [Feature] 프로젝트 상세 조회 API
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/CreateProjectUserRequest.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectDetailResponse.java
  module-api/src/main/java/com/back2basics/domain/projectstep/controller/ProjectStepController.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/request/CreateProjectStepRequest.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/request/UpdateApprovalStatusRequest.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/request/UpdateProjectStepRequest.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/response/ProjectStepSimpleResponse.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserCompanyResponse.java
  module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/in/command/ProjectCreateCommand.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectDetailResult.java
  module-core/src/main/java/com/back2basics/projectstep/model/ProjectFeedbackStepStatus.java
  module-core/src/main/java/com/back2basics/projectstep/model/ProjectStep.java
  module-core/src/main/java/com/back2basics/projectstep/model/ProjectStepStatus.java
  module-core/src/main/java/com/back2basics/projectstep/port/in/command/CreateProjectStepCommand.java
  module-core/src/main/java/com/back2basics/projectstep/port/in/command/UpdateProjectStepCommand.java
  module-core/src/main/java/com/back2basics/projectstep/port/in/command/UpdateProjectStepUseCase.java
  module-core/src/main/java/com/back2basics/projectstep/port/out/ReadProjectStepPort.java
  module-core/src/main/java/com/back2basics/projectstep/service/CreateProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/UpdateProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/result/ProjectStepSimpleResult.java
  module-core/src/main/java/com/back2basics/projectstep/service/result/ReadProjectStepResult.java
  module-core/src/main/java/com/back2basics/projectuser/model/ProjectUser.java
  module-core/src/main/java/com/back2basics/projectuser/port/out/ProjectUserQueryPort.java
  module-core/src/main/java/com/back2basics/user/service/result/UserCompanyResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/adapter/ReadProjectStepAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/ProjectUserEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/ProjectUserEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/ProjectUserMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/adapter/ProjectUserQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/adapter/SaveProjectUserAdapter.java
Labels: ✨ 기능 추가, ♻️ 리팩토링, 유진 🐱, 💬 SHOW

#246 [Feature] 작성자 IP 추가
  module-api/src/main/java/com/back2basics/domain/answer/controller/AnswerController.java
  module-api/src/main/java/com/back2basics/domain/answer/dto/response/AnswerReadResponse.java
  module-api/src/main/java/com/back2basics/domain/comment/controller/CommentController.java
  module-api/src/main/java/com/back2basics/domain/comment/dto/response/CommentReadResponse.java
  module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/post/dto/response/PostCreateResponse.java
  module-api/src/main/java/com/back2basics/domain/post/dto/response/PostReadResponse.java
  module-api/src/main/java/com/back2basics/domain/question/controller/QuestionController.java
  module-api/src/main/java/com/back2basics/domain/question/dto/response/QuestionResponse.java
  module-api/src/main/java/com/back2basics/global/config/WebConfig.java
  module-api/src/main/java/com/back2basics/global/security/config/SecurityConfig.java
  module-api/src/main/java/com/back2basics/global/security/filter/IpInjectionFilter.java
  module-api/src/main/java/com/back2basics/global/utils/ClientUtils.java
  module-core/src/main/java/com/back2basics/answer/model/Answer.java
  module-core/src/main/java/com/back2basics/answer/port/in/AnswerCreateUseCase.java
  module-core/src/main/java/com/back2basics/answer/port/in/AnswerUpdateUseCase.java
  module-core/src/main/java/com/back2basics/answer/service/AnswerCreateService.java
  module-core/src/main/java/com/back2basics/answer/service/AnswerUpdateService.java
  module-core/src/main/java/com/back2basics/answer/service/result/AnswerReadResult.java
  module-core/src/main/java/com/back2basics/comment/model/Comment.java
  module-core/src/main/java/com/back2basics/comment/port/in/CommentCreateUseCase.java
  module-core/src/main/java/com/back2basics/comment/port/in/CommentUpdateUseCase.java
  module-core/src/main/java/com/back2basics/comment/port/out/CommentUpdatePort.java
  module-core/src/main/java/com/back2basics/comment/service/CommentCreateService.java
  module-core/src/main/java/com/back2basics/comment/service/CommentUpdateService.java
  module-core/src/main/java/com/back2basics/comment/service/result/CommentReadResult.java
  module-core/src/main/java/com/back2basics/post/model/Post.java
  module-core/src/main/java/com/back2basics/post/port/in/PostCreateUseCase.java
  module-core/src/main/java/com/back2basics/post/port/in/PostUpdateUseCase.java
  module-core/src/main/java/com/back2basics/post/service/PostCreateService.java
  module-core/src/main/java/com/back2basics/post/service/PostUpdateService.java
  module-core/src/main/java/com/back2basics/post/service/result/PostCreateResult.java
  module-core/src/main/java/com/back2basics/post/service/result/PostReadResult.java
  module-core/src/main/java/com/back2basics/question/model/Question.java
  module-core/src/main/java/com/back2basics/question/port/in/QuestionCreateUseCase.java
  module-core/src/main/java/com/back2basics/question/port/in/QuestionStatusUpdateUseCase.java
  module-core/src/main/java/com/back2basics/question/port/in/QuestionUpdateUseCase.java
  module-core/src/main/java/com/back2basics/question/port/out/QuestionStatusUpdatePort.java
  module-core/src/main/java/com/back2basics/question/port/out/QuestionUpdatePort.java
  module-core/src/main/java/com/back2basics/question/service/QuestionCreateService.java
  module-core/src/main/java/com/back2basics/question/service/QuestionStatusUpdateService.java
  module-core/src/main/java/com/back2basics/question/service/QuestionUpdateService.java
  module-core/src/main/java/com/back2basics/question/service/result/QuestionResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/answer/AnswerEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/answer/AnswerEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/answer/AnswerMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/answer/adapter/AnswerReadJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/CommentEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/CommentMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/adapter/CommentUpdateJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/question/QuestionEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/question/QuestionMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/question/adapter/QuestionStatusUpdateJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/question/adapter/QuestionUpdateJpaAdapter.java
  module-infra/src/main/java/com/back2basics/security/model/CustomUserDetails.java
Labels: ✨ 기능 추가, 승우 🐯, 💬 SHOW

#252 [Feature] Create deploy.yml
  .github/workflows/deploy.yml
Labels: ⚙️ 기타 작업, 유진 🐱, 🚢 SHIP

#254 [Docs] swagger 응답에 json 포맷 오류 수정
  module-api/src/main/java/com/back2basics/domain/answer/swagger/AnswerApiDocs.java
  module-api/src/main/java/com/back2basics/domain/answer/swagger/AnswerDocsResult.java
  module-api/src/main/java/com/back2basics/domain/comment/swagger/CommentApiDocs.java
  module-api/src/main/java/com/back2basics/domain/comment/swagger/CommentDocsResult.java
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostDocsResult.java
  module-api/src/main/java/com/back2basics/domain/question/swagger/QuestionDocsResult.java
Labels: 📄 문서, 승우 🐯

#261 [Feature] 허용 도메인 수정
  module-api/src/main/java/com/back2basics/global/security/config/SecurityConfig.java
Labels: ⚙️ 기타 작업, 유진 🐱

#262 [Feature] cookie 설정 수정
  module-api/src/main/java/com/back2basics/global/security/config/SecurityConfig.java
  module-infra/src/main/java/com/back2basics/util/CookieUtil.java
Labels: ⚙️ 기타 작업, 유진 🐱

#278 [Feature] Company bizNo(사업자 등록번호) 타입 변경
  module-api/src/main/java/com/back2basics/domain/company/dto/request/CreateCompanyRequest.java
  module-api/src/main/java/com/back2basics/domain/company/dto/request/UpdateCompanyRequest.java
  module-api/src/main/java/com/back2basics/domain/company/dto/response/ReadCompanyResponse.java
  module-core/src/main/java/com/back2basics/company/model/Company.java
  module-core/src/main/java/com/back2basics/company/port/in/command/CreateCompanyCommand.java
  module-core/src/main/java/com/back2basics/company/port/in/command/UpdateCompanyCommand.java
  module-core/src/main/java/com/back2basics/company/service/result/ReadCompanyResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntity.java
Labels: ✨ 기능 추가, 정인 🐻, 💬 SHOW

#281 [Deploy] 배포
  module-api/src/main/java/com/back2basics/domain/company/dto/request/CreateCompanyRequest.java
  module-api/src/main/java/com/back2basics/domain/company/dto/request/UpdateCompanyRequest.java
  module-api/src/main/java/com/back2basics/domain/company/dto/response/ReadCompanyResponse.java
  module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
  module-api/src/main/java/com/back2basics/domain/user/controller/code/UserResponseCode.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/ChangePasswordRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/ResetPasswordByTokenRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/ResetPasswordRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/SendMailRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/UserCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/request/UserUpdateRequest.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserInfoResponse.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserSimpleResponse.java
  module-core/src/main/java/com/back2basics/company/model/Company.java
  module-core/src/main/java/com/back2basics/company/port/in/command/CreateCompanyCommand.java
  module-core/src/main/java/com/back2basics/company/port/in/command/UpdateCompanyCommand.java
  module-core/src/main/java/com/back2basics/company/service/result/ReadCompanyResult.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/user/model/Role.java
  module-core/src/main/java/com/back2basics/user/model/User.java
  module-core/src/main/java/com/back2basics/user/port/in/UpdateUserUseCase.java
  module-core/src/main/java/com/back2basics/user/port/in/UserQueryUseCase.java
  module-core/src/main/java/com/back2basics/user/port/in/command/UserCreateCommand.java
  module-core/src/main/java/com/back2basics/user/port/out/UserQueryPort.java
  module-core/src/main/java/com/back2basics/user/service/UpdateUserService.java
  module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
  module-core/src/main/java/com/back2basics/user/service/result/UserInfoResult.java
  module-core/src/main/java/com/back2basics/user/service/result/UserSimpleResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/repository/UserEntityRepository.java
Labels: ⚙️ 기타 작업, 유진 🐱

#296 [Feature] customUserDetails가 null일때 글로벌예외 등록(임시)
  module-api/src/main/java/com/back2basics/global/handler/GlobalExceptionHandler.java
Labels: ✨ 기능 추가, 승우 🐯, 💬 SHOW

#299 [Bug] osiv false로 인한 에러 해결
  module-api/src/main/resources/application.yml
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostReadJpaAdapter.java
Labels: ✨ 기능 추가, 승우 🐯, 🚢 SHIP

#301 [Feature] 회원별 프로젝트 목록 및 프로젝트 단계 상세 조회
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/projectstep/controller/ProjectStepController.java
  module-api/src/main/java/com/back2basics/domain/projectstep/controller/code/ProjectStepResponseCode.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/response/DetailProjectStepResponse.java
  module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectGetResult.java
  module-core/src/main/java/com/back2basics/projectstep/model/ProjectStep.java
  module-core/src/main/java/com/back2basics/projectstep/port/in/ReadProjectStepUseCase.java
  module-core/src/main/java/com/back2basics/projectstep/port/out/ReadProjectStepPort.java
  module-core/src/main/java/com/back2basics/projectstep/service/ReadProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/result/DetailProjectStepResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/ProjectUserEntityRepository.java
Labels: ✨ 기능 추가, 진효 🐰, 🚢 SHIP

#305 [Feature] 게시글 조회 추가, ip 헤더 분기 추가 등 기타 작업
  module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostApiDocs.java
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostDocsResult.java
  module-api/src/main/java/com/back2basics/domain/question/controller/QuestionResponseCode.java
  module-api/src/main/java/com/back2basics/global/utils/ClientUtils.java
  module-core/src/main/java/com/back2basics/post/port/in/PostSearchUseCase.java
  module-core/src/main/java/com/back2basics/post/port/in/command/PostSearchCommand.java
  module-core/src/main/java/com/back2basics/post/port/out/PostSearchPort.java
  module-core/src/main/java/com/back2basics/post/service/PostSearchService.java
  module-core/src/main/java/com/back2basics/question/model/Question.java
  module-core/src/main/java/com/back2basics/question/model/QuestionStatus.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostSearchJpaAdapter.java
Labels: ✨ 기능 추가, ♻️ 리팩토링, 승우 🐯, 🚢 SHIP

#306 [Feature] 프로젝트 멤버 할당
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/controller/code/ProjectResponseCode.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectCreateRequest.java
  module-core/src/main/java/com/back2basics/project/port/in/command/ProjectCreateCommand.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/projectuser/model/ProjectUser.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/ProjectUserEntity.java
Labels: ✨ 기능 추가, ❌ 삭제, ♻️ 리팩토링, 진효 🐰, 🚢 SHIP

#310 [Feature] 게시글을 프로젝트가 아닌 단계별 게시글로 수정
  module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/post/dto/request/PostCreateApiRequest.java
  module-api/src/main/java/com/back2basics/domain/post/dto/request/PostSearchRequest.java
  module-api/src/main/java/com/back2basics/domain/post/dto/response/PostReadResponse.java
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostApiDocs.java
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostDocsResult.java
  module-core/src/main/java/com/back2basics/post/model/Post.java
  module-core/src/main/java/com/back2basics/post/port/in/PostCreateUseCase.java
  module-core/src/main/java/com/back2basics/post/port/in/PostReadUseCase.java
  module-core/src/main/java/com/back2basics/post/port/in/PostSearchUseCase.java
  module-core/src/main/java/com/back2basics/post/port/in/command/PostCreateCommand.java
  module-core/src/main/java/com/back2basics/post/port/in/command/PostSearchCommand.java
  module-core/src/main/java/com/back2basics/post/port/in/command/PostSoftDeleteCommand.java
  module-core/src/main/java/com/back2basics/post/port/out/PostReadPort.java
  module-core/src/main/java/com/back2basics/post/port/out/PostSearchPort.java
  module-core/src/main/java/com/back2basics/post/service/PostCreateService.java
  module-core/src/main/java/com/back2basics/post/service/PostReadService.java
  module-core/src/main/java/com/back2basics/post/service/PostSearchService.java
  module-core/src/main/java/com/back2basics/post/service/PostUpdateService.java
  module-core/src/main/java/com/back2basics/post/service/result/PostReadResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostDeleteJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostReadJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostSearchJpaAdapter.java
Labels: ✨ 기능 추가, ♻️ 리팩토링, 승우 🐯, 🚢 SHIP

#318 [Fix] 잘못된 시간대 반환 수정
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserInfoResponse.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserSimpleResponse.java
Labels: 🐞 버그, 유진 🐱, 🚢 SHIP

#319 [Fix] 잘못된 시간대 반환 수정
  module-api/src/main/resources/application.yml
Labels: 🐞 버그, 유진 🐱, 🚢 SHIP

#325 [Feature] 관리자 대시보드 최근 등록된 회사 기능 구현
  module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
  module-api/src/main/java/com/back2basics/domain/company/dto/response/ReadRecentCompanyResponse.java
  module-core/src/main/java/com/back2basics/company/port/in/ReadCompanyUseCase.java
  module-core/src/main/java/com/back2basics/company/port/out/ReadCompanyPort.java
  module-core/src/main/java/com/back2basics/company/service/ReadCompanyService.java
  module-core/src/main/java/com/back2basics/company/service/result/ReadRecentCompanyResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/ReadCompanyJpaAdapter.java
Labels: ✨ 기능 추가, 정인 🐻, 💬 SHOW

#331 [Feature] 회사 softDelete시 해당 회사 속한 회원 company_id Null로 지정
  module-core/src/main/java/com/back2basics/company/service/DeleteCompanyService.java
  module-core/src/main/java/com/back2basics/user/model/User.java
  module-core/src/main/java/com/back2basics/user/port/out/UserQueryPort.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
Labels: ✨ 기능 추가, ✅ 리뷰 승인, 정인 🐻, 💬 SHOW

#333 [Feature] 회사 softDelete시 해당 회사에 속한 회원 softDelete 적용 기능 구현
  module-core/src/main/java/com/back2basics/company/service/DeleteCompanyService.java
  module-core/src/main/java/com/back2basics/user/port/out/UserCommandPort.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserCommandAdapter.java
Labels: ✨ 기능 추가, 정인 🐻, 💬 SHOW

#335 [Feature] Post 최근 등록 5개 기능 구현
  module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/post/dto/response/ReadRecentPostResponse.java
  module-core/src/main/java/com/back2basics/post/port/in/PostReadUseCase.java
  module-core/src/main/java/com/back2basics/post/port/out/PostReadPort.java
  module-core/src/main/java/com/back2basics/post/service/PostReadService.java
  module-core/src/main/java/com/back2basics/post/service/result/ReadRecentPostResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostReadJpaAdapter.java
Labels: ✨ 기능 추가, 정인 🐻

#341 Feature/334
  module-core/src/main/java/com/back2basics/comment/service/CommentCreateService.java
  module-core/src/main/java/com/back2basics/comment/service/notification/CommentNotificationSender.java
  module-core/src/main/java/com/back2basics/notify/model/NotificationType.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostReadJpaAdapter.java
Labels: ✨ 기능 추가, 승우 🐯, 💬 SHOW

#345 [Refactor] project 클래스 및 주석 삭제
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectListResponse.java
  module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/in/TestUseCase.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/port/out/TestPort.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
  module-core/src/main/java/com/back2basics/project/service/TestService.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectListResult.java
  module-core/src/main/java/com/back2basics/projectuser/model/ProjectUser.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/TestAdapter.java
Labels: ❌ 삭제, ♻️ 리팩토링, 진효 🐰

#348 [Refactor] 회사 테이블 명 변경
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntity.java
Labels: ♻️ 리팩토링, 정인 🐻, 💬 SHOW

#358 [Feature] 게시글 원하는 필드만 리턴, 프로젝트 기한 지나면 지연 상태로 변경
  module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/post/dto/response/PostDetailReadResponse.java
  module-api/src/main/java/com/back2basics/domain/post/dto/response/PostSummaryReadResponse.java
  module-api/src/main/java/com/back2basics/domain/post/swagger/PostApiDocs.java
  module-api/src/test/java/com/back2basics/post/service/PostReadServiceTest.java
  module-core/src/main/java/com/back2basics/post/model/Post.java
  module-core/src/main/java/com/back2basics/post/port/in/PostReadUseCase.java
  module-core/src/main/java/com/back2basics/post/port/in/PostSearchUseCase.java
  module-core/src/main/java/com/back2basics/post/service/PostReadService.java
  module-core/src/main/java/com/back2basics/post/service/PostSearchService.java
  module-core/src/main/java/com/back2basics/post/service/result/PostDetailReadResult.java
  module-core/src/main/java/com/back2basics/post/service/result/PostSummaryReadResult.java
  module-core/src/main/java/com/back2basics/project/model/ProjectStatus.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostReadJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostSearchJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/projection/PostDetailResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/projection/PostSummaryResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectMapper.java
Labels: ✨ 기능 추가, ♻️ 리팩토링, 승우 🐯

#363 [Feature] 게시글에 파일 업로드/수정 기능 추가, 프로젝트 endDate에 따른 상태 변경 수정
  module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/post/dto/response/PostDetailReadResponse.java
  module-api/src/main/resources/application.yml
  module-core/build.gradle
  module-core/src/main/java/com/back2basics/infra/s3/S3Util.java
  module-core/src/main/java/com/back2basics/post/file/File.java
  module-core/src/main/java/com/back2basics/post/file/FileDeletePort.java
  module-core/src/main/java/com/back2basics/post/file/FileReadPort.java
  module-core/src/main/java/com/back2basics/post/file/FileSavePort.java
  module-core/src/main/java/com/back2basics/post/file/FileUploadService.java
  module-core/src/main/java/com/back2basics/post/model/Post.java
  module-core/src/main/java/com/back2basics/post/port/in/PostCreateUseCase.java
  module-core/src/main/java/com/back2basics/post/port/in/PostUpdateUseCase.java
  module-core/src/main/java/com/back2basics/post/port/out/PostCreatePort.java
  module-core/src/main/java/com/back2basics/post/port/out/PostUpdatePort.java
  module-core/src/main/java/com/back2basics/post/service/PostCreateService.java
  module-core/src/main/java/com/back2basics/post/service/PostUpdateService.java
  module-core/src/main/java/com/back2basics/post/service/result/PostDetailReadResult.java
  module-infra/build.gradle
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostCreateJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostReadJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostSearchJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostUpdateJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/projection/PostDetailProjection.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/projection/PostSummaryProjection.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/file/FileDeleteAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/file/FileEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/file/FileEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/file/FileMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/file/FileReadAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/post/file/FileSaveAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
  module-infra/src/main/java/com/back2basics/config/S3Config.java
Labels: ✨ 기능 추가, 승우 🐯

#364 [Feature] 프로젝트에 할당된 업체 삭제
  module-api/src/main/java/com/back2basics/domain/assignment/controller/AssignmentController.java
  module-api/src/main/java/com/back2basics/domain/assignment/controller/code/AssignmentResponseCode.java
  module-core/src/main/java/com/back2basics/assignment/model/Assignment.java
  module-core/src/main/java/com/back2basics/assignment/port/in/DeleteAssignmentUseCase.java
  module-core/src/main/java/com/back2basics/assignment/port/out/AssignmentQueryPort.java
  module-core/src/main/java/com/back2basics/assignment/port/out/DeleteAssignmentPort.java
  module-core/src/main/java/com/back2basics/assignment/service/DeleteAssignmentService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/AssignmentEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/AssignmentMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/adapter/AssignmentQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/adapter/DeleteAssignmentAdapter.java
Labels: ✨ 기능 추가, 진효 🐰, 🚢 SHIP

#367 [Feature] 게시글,댓글에 멘션 기능 추가
  module-core/src/main/java/com/back2basics/notify/model/NotificationType.java
  module-core/src/main/java/com/back2basics/post/service/PostCreateService.java
  module-core/src/main/java/com/back2basics/post/service/notification/PostNotificationSender.java
  module-core/src/main/java/com/back2basics/project/port/out/ProjectMemberQueryPort.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/AssignmentEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ProjectMemberQueryAdapter.java
Labels: ✨ 기능 추가, 승우 🐯, 🚢 SHIP

#375 [Refactor] 프로젝트 상세 조회 및 전체 목록 response 수정
  module-api/src/main/java/com/back2basics/domain/assignment/dto/response/AssignProjectListResponse.java
  module-api/src/main/java/com/back2basics/domain/assignment/dto/response/AssignUserResponse.java
  module-api/src/main/java/com/back2basics/domain/company/dto/response/CompanySummaryResponse.java
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectDetailResponse.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectListResponse.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/response/ProjectStepSimpleResponse.java
  module-core/src/main/java/com/back2basics/assignment/service/result/AssignProjectListResult.java
  module-core/src/main/java/com/back2basics/assignment/service/result/AssignUserResult.java
  module-core/src/main/java/com/back2basics/company/service/result/CompanySummaryResult.java
  module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectDetailResult.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectListResult.java
  module-core/src/main/java/com/back2basics/projectstep/service/ReadProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/result/ProjectStepSimpleResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
Labels: ❌ 삭제, ♻️ 리팩토링, 진효 🐰

#387 [Feature] project step 리팩토링
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectDetailResponse.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectGetResponse.java
  module-api/src/main/java/com/back2basics/domain/projectstep/controller/ProjectStepController.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/request/CreateProjectStepRequest.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/request/UpdateProjectStepRequest.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/response/DetailProjectStepResponse.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/response/ProjectStepResponse.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/response/ProjectStepSimpleResponse.java
  module-api/src/main/java/com/back2basics/domain/projectstep/dto/response/ReadProjectStepResponse.java
  module-core/src/main/java/com/back2basics/approval/model/ApprovalRequest.java
  module-core/src/main/java/com/back2basics/approval/model/ApprovalRequestStatus.java
  module-core/src/main/java/com/back2basics/approval/model/ApprovalUser.java
  module-core/src/main/java/com/back2basics/approval/model/ApprovalUserStatus.java
  module-core/src/main/java/com/back2basics/infra/validation/validator/ProjectValidator.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectDetailResult.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectGetResult.java
  module-core/src/main/java/com/back2basics/projectstep/model/ProjectStep.java
  module-core/src/main/java/com/back2basics/projectstep/model/ProjectStepStatus.java
  module-core/src/main/java/com/back2basics/projectstep/port/in/CreateProjectStepUseCase.java
  module-core/src/main/java/com/back2basics/projectstep/port/in/ReadProjectStepUseCase.java
  module-core/src/main/java/com/back2basics/projectstep/port/in/UpdateProjectStepUseCase.java
  module-core/src/main/java/com/back2basics/projectstep/port/in/command/CreateProjectStepCommand.java
  module-core/src/main/java/com/back2basics/projectstep/port/in/command/UpdateProjectStepCommand.java
  module-core/src/main/java/com/back2basics/projectstep/port/out/ReadProjectStepPort.java
  module-core/src/main/java/com/back2basics/projectstep/port/out/SaveProjectStepPort.java
  module-core/src/main/java/com/back2basics/projectstep/service/CreateProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/DeleteProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/ReadProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/UpdateProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/result/DetailProjectStepResult.java
  module-core/src/main/java/com/back2basics/projectstep/service/result/ProjectStepResult.java
  module-core/src/main/java/com/back2basics/projectstep/service/result/ProjectStepSimpleResult.java
  module-core/src/main/java/com/back2basics/projectstep/service/result/ReadProjectStepResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/entity/ApprovalRequestEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/entity/ApprovalUserEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/adapter/ReadProjectStepAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/adapter/SaveProjectStepAdapter.java
  module-infra/src/main/java/com/back2basics/util/RedisUtil.java
Labels: ♻️ 리팩토링, 유진 🐱, 💬 SHOW

#388 [Feature] 프로젝트 생성 로직 변경
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectUpdateRequest.java
  module-core/src/main/java/com/back2basics/assignment/model/Assignment.java
  module-core/src/main/java/com/back2basics/assignment/port/out/AssignmentQueryPort.java
  module-core/src/main/java/com/back2basics/project/model/Project.java
  module-core/src/main/java/com/back2basics/project/port/in/command/ProjectUpdateCommand.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/AssignmentEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/AssignmentMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/adapter/AssignmentQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/adapter/SaveAssignmentAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/SaveProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/UpdateProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
Labels: ❌ 삭제, ♻️ 리팩토링, 진효 🐰

#391 [Fix] projectStep 충돌 해결
  module-core/src/main/java/com/back2basics/projectstep/model/ProjectStep.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/adapter/SaveProjectStepAdapter.java
Labels: ❌ 삭제, 진효 🐰

#392 [Refactor] projectStep 변수명 변경
  module-core/src/main/java/com/back2basics/projectstep/service/UpdateProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/result/ProjectStepResult.java
Labels: ♻️ 리팩토링, 진효 🐰

#401 [Hotfix] 게시글 수정에 단계 수정 추가
  module-api/src/main/java/com/back2basics/domain/board/dto/request/PostUpdateRequest.java
  module-api/src/main/java/com/back2basics/global/security/config/SecurityConfig.java
  module-api/src/main/java/com/back2basics/mongodb/TestController.java
  module-api/src/main/resources/application.yml
  module-core/src/main/java/com/back2basics/board/post/model/Post.java
  module-core/src/main/java/com/back2basics/board/post/port/in/command/PostUpdateCommand.java
  module-infra/build.gradle
  module-infra/src/main/java/com/back2basics/adapter/external/mongodb/TestDocument.java
  module-infra/src/main/java/com/back2basics/adapter/external/mongodb/TestDocumentRepository.java
  module-infra/src/main/java/com/back2basics/adapter/external/mongodb/TestDocumentService.java
Labels: ✨ 기능 추가, 승우 🐯, 🚢 SHIP

#404 [Feature] 단계 승인 기능
  module-api/src/main/java/com/back2basics/domain/approval/controller/ApprovalController.java
  module-api/src/main/java/com/back2basics/domain/approval/controller/code/ApprovalResponseCode.java
  module-api/src/main/java/com/back2basics/domain/approval/dto/request/CreateApprovalRequest.java
  module-api/src/main/java/com/back2basics/domain/approval/dto/request/UpdateApprovalRequest.java
  module-api/src/main/java/com/back2basics/domain/approval/dto/response/ApprovalInfoResponse.java
  module-api/src/main/java/com/back2basics/domain/approval/dto/response/ApproverIdsResponse.java
  module-api/src/main/java/com/back2basics/domain/approval/dto/response/ApproverResponse.java
  module-core/src/main/java/com/back2basics/approval/model/ApprovalRequest.java
  module-core/src/main/java/com/back2basics/approval/model/ApprovalResponse.java
  module-core/src/main/java/com/back2basics/approval/model/ApprovalResponseStatus.java
  module-core/src/main/java/com/back2basics/approval/port/in/CreateApprovalRequestUseCase.java
  module-core/src/main/java/com/back2basics/approval/port/in/ReadApprovalUseCase.java
  module-core/src/main/java/com/back2basics/approval/port/in/UpdateApprovalResponseUseCase.java
  module-core/src/main/java/com/back2basics/approval/port/in/command/CreateApprovalCommand.java
  module-core/src/main/java/com/back2basics/approval/port/in/command/UpdateApprovalCommand.java
  module-core/src/main/java/com/back2basics/approval/port/out/ApprovalRequestCommandPort.java
  module-core/src/main/java/com/back2basics/approval/port/out/ApprovalRequestQueryPort.java
  module-core/src/main/java/com/back2basics/approval/port/out/ApprovalResponseCommandPort.java
  module-core/src/main/java/com/back2basics/approval/port/out/ApprovalResponseQueryPort.java
  module-core/src/main/java/com/back2basics/approval/service/CreateApprovalRequestRequestService.java
  module-core/src/main/java/com/back2basics/approval/service/ReadApprovalService.java
  module-core/src/main/java/com/back2basics/approval/service/UpdateApprovalResponseService.java
  module-core/src/main/java/com/back2basics/approval/service/result/ApprovalInfoResult.java
  module-core/src/main/java/com/back2basics/approval/service/result/ApproverIdsResult.java
  module-core/src/main/java/com/back2basics/approval/service/result/ApproverResult.java
  module-core/src/main/java/com/back2basics/infra/exception/approval/ApprovalErrorCode.java
  module-core/src/main/java/com/back2basics/infra/exception/approval/ApprovalException.java
  module-core/src/main/java/com/back2basics/infra/exception/projectstep/ProjectStepException.java
  module-core/src/main/java/com/back2basics/infra/validation/validator/ApprovalValidator.java
  module-core/src/main/java/com/back2basics/infra/validation/validator/ProjectStepValidator.java
  module-core/src/main/java/com/back2basics/infra/validation/validator/UserValidator.java
  module-core/src/main/java/com/back2basics/projectstep/port/out/ReadProjectStepPort.java
  module-core/src/main/java/com/back2basics/user/port/out/UserQueryPort.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/adapter/ApprovalRequestCommandAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/adapter/ApprovalRequestQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/adapter/ApprovalResponseCommandAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/adapter/ApprovalResponseQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/entity/ApprovalRequestEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/entity/ApprovalResponseEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/mapper/ApprovalRequestMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/mapper/ApprovalResponseMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/repository/ApprovalRequestEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/repository/ApprovalResponseEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/adapter/ReadProjectStepAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
Labels: ✨ 기능 추가, 유진 🐱, 💬 SHOW

#407 [Feature] 댓글, 게시글 생성/수정 시 멘션 기능 추가, 유저 검색 및 파일 업로드 관련 예외 처리 추가
  module-api/src/main/java/com/back2basics/domain/user/controller/UserController.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserSummaryResponse.java
  module-api/src/main/java/com/back2basics/global/handler/GlobalExceptionHandler.java
  module-api/src/main/resources/application.yml
  module-common/src/main/java/com/back2basics/global/response/code/CommonErrorCode.java
  module-core/src/main/java/com/back2basics/board/post/service/PostCreateService.java
  module-core/src/main/java/com/back2basics/board/post/service/PostUpdateService.java
  module-core/src/main/java/com/back2basics/comment/service/CommentCreateService.java
  module-core/src/main/java/com/back2basics/comment/service/CommentUpdateService.java
  module-core/src/main/java/com/back2basics/mention/MentionNotificationSender.java
  module-core/src/main/java/com/back2basics/mention/MentionUtils.java
  module-core/src/main/java/com/back2basics/notify/model/NotificationType.java
  module-core/src/main/java/com/back2basics/user/port/in/UserSearchUseCase.java
  module-core/src/main/java/com/back2basics/user/port/out/UserQueryPort.java
  module-core/src/main/java/com/back2basics/user/port/out/UserSearchPort.java
  module-core/src/main/java/com/back2basics/user/service/UserSearchService.java
  module-core/src/main/java/com/back2basics/user/service/result/UserSummaryResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserSearchAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/repository/UserEntityRepository.java
  module-infra/src/main/java/com/back2basics/config/FileUploadConfig.java
Labels: ✨ 기능 추가, ♻️ 리팩토링, 승우 🐯, 🚢 SHIP

#409 [Feature] 진행률 계산 기능 구현
  module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectDetailResponse.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectListResponse.java
  module-api/src/main/java/com/back2basics/domain/projectstep/controller/ProjectStepController.java
  module-api/src/main/java/com/back2basics/domain/projectstep/controller/code/ProjectStepResponseCode.java
  module-api/src/main/java/com/back2basics/domain/user/dto/response/UserSummaryResponse.java
  module-core/src/main/java/com/back2basics/project/model/Project.java
  module-core/src/main/java/com/back2basics/project/port/in/UpdateProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/out/SaveProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectDetailResult.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectListResult.java
  module-core/src/main/java/com/back2basics/projectstep/model/ProjectStep.java
  module-core/src/main/java/com/back2basics/projectstep/model/ProjectStepStatus.java
  module-core/src/main/java/com/back2basics/projectstep/model/StepApprovalStatus.java
  module-core/src/main/java/com/back2basics/projectstep/port/in/UpdateProjectStepUseCase.java
  module-core/src/main/java/com/back2basics/projectstep/port/out/ReadProjectStepPort.java
  module-core/src/main/java/com/back2basics/projectstep/port/out/SaveProjectStepPort.java
  module-core/src/main/java/com/back2basics/projectstep/service/UpdateProjectStepService.java
  module-core/src/main/java/com/back2basics/user/service/result/UserSummaryResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/SaveProjectAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/adapter/ReadProjectStepAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/adapter/SaveProjectStepAdapter.java
Labels: ✨ 기능 추가, ❌ 삭제, ♻️ 리팩토링, 진효 🐰

#410 [Feature] 승인 요청 알림 서비스
  module-core/src/main/java/com/back2basics/approval/model/ApprovalResponse.java
  module-core/src/main/java/com/back2basics/approval/port/out/ApprovalRequestCommandPort.java
  module-core/src/main/java/com/back2basics/approval/service/CreateApprovalRequestRequestService.java
  module-core/src/main/java/com/back2basics/approval/service/ReadApprovalService.java
  module-core/src/main/java/com/back2basics/approval/service/UpdateApprovalResponseService.java
  module-core/src/main/java/com/back2basics/notify/model/NotificationType.java
  module-core/src/main/java/com/back2basics/user/service/UserSearchService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/adapter/ApprovalRequestCommandAdapter.java
Labels: ✨ 기능 추가, 유진 🐱, 💬 SHOW

#411 [Feature] 회사 수정 시 중복확인 기능 구현 및 유효성검사 추가
  module-api/src/main/java/com/back2basics/domain/company/dto/request/CreateCompanyRequest.java
  module-api/src/main/java/com/back2basics/domain/company/dto/request/UpdateCompanyRequest.java
  module-core/src/main/java/com/back2basics/company/port/out/UpdateCompanyPort.java
  module-core/src/main/java/com/back2basics/company/service/UpdateCompanyService.java
  module-core/src/main/java/com/back2basics/infra/validation/validator/CompanyValidator.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/UpdateCompanyJpaAdapter.java
Labels: ✨ 기능 추가, 정인 🐻

#421 [Feature] 회원 조회 API 수정
  module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
  module-core/src/main/java/com/back2basics/user/port/in/UserQueryUseCase.java
  module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
Labels: ✨ 기능 추가, 정인 🐻

#423 [Feature] 프로젝트 할당 멤버 알림 전송
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-core/src/main/java/com/back2basics/assignment/service/notification/AssignmentNotificationSender.java
  module-core/src/main/java/com/back2basics/notify/model/NotificationType.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
Labels: ✨ 기능 추가, 진효 🐰, 🚢 SHIP

#427 [Refactor] validation 적용
  module-core/src/main/java/com/back2basics/assignment/service/DeleteAssignmentService.java
  module-core/src/main/java/com/back2basics/infra/validation/validator/ProjectStepValidator.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
  module-core/src/main/java/com/back2basics/projectstep/service/CreateProjectStepService.java
  module-core/src/main/java/com/back2basics/projectstep/service/UpdateProjectStepService.java
Labels: ♻️ 리팩토링, 진효 🐰

#435 [Feature] 프로젝트 상세 조회 response 수정
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectDetailResponse.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectDetailResult.java
Labels: ✨ 기능 추가, 진효 🐰

#437 [Refactor] 프로젝트 목록 조회 api 통합
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
Labels: ♻️ 리팩토링, 진효 🐰

#441 [Feature] 검색 조회 api 통합
  module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectListResponse.java
  module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
  module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
Labels: ✨ 기능 추가, 진효 🐰

#453 [Feature] 게시글 링크 첨부 기능 구현, 기타 핫픽스
  module-api/src/main/java/com/back2basics/domain/board/dto/request/PostCreateRequest.java
  module-api/src/main/java/com/back2basics/domain/board/dto/request/PostUpdateRequest.java
  module-api/src/main/java/com/back2basics/domain/board/dto/response/PostDetailReadResponse.java
  module-api/src/main/java/com/back2basics/domain/board/dto/response/PostSummaryReadResponse.java
  module-api/src/main/java/com/back2basics/domain/comment/dto/response/CommentReadResponse.java
  module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
  module-api/src/main/java/com/back2basics/domain/user/controller/UserController.java
  module-api/src/main/java/com/back2basics/mongodb/TestController.java
  module-core/src/main/java/com/back2basics/board/link/model/Link.java
  module-core/src/main/java/com/back2basics/board/link/port/out/LinkDeletePort.java
  module-core/src/main/java/com/back2basics/board/link/port/out/LinkReadPort.java
  module-core/src/main/java/com/back2basics/board/link/port/out/LinkSavePort.java
  module-core/src/main/java/com/back2basics/board/link/service/LinkCreateService.java
  module-core/src/main/java/com/back2basics/board/link/service/LinkUpdateService.java
  module-core/src/main/java/com/back2basics/board/post/model/Post.java
  module-core/src/main/java/com/back2basics/board/post/port/in/command/PostCreateCommand.java
  module-core/src/main/java/com/back2basics/board/post/port/in/command/PostUpdateCommand.java
  module-core/src/main/java/com/back2basics/board/post/service/PostCreateService.java
  module-core/src/main/java/com/back2basics/board/post/service/PostUpdateService.java
  module-core/src/main/java/com/back2basics/board/post/service/result/PostDetailReadResult.java
  module-core/src/main/java/com/back2basics/board/post/service/result/PostSummaryReadResult.java
  module-core/src/main/java/com/back2basics/comment/model/Comment.java
  module-core/src/main/java/com/back2basics/comment/service/result/CommentReadResult.java
  module-core/src/main/java/com/back2basics/user/port/in/CreateUserUseCase.java
  module-core/src/main/java/com/back2basics/user/port/in/UserSearchUseCase.java
  module-core/src/main/java/com/back2basics/user/port/out/UserSearchPort.java
  module-core/src/main/java/com/back2basics/user/service/CreateUserService.java
  module-core/src/main/java/com/back2basics/user/service/UserSearchService.java
  module-infra/src/main/java/com/back2basics/adapter/external/mongodb/TestDocument.java
  module-infra/src/main/java/com/back2basics/adapter/external/mongodb/TestDocumentRepository.java
  module-infra/src/main/java/com/back2basics/adapter/external/mongodb/TestDocumentService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/link/LinkEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/link/LinkEntityRepository.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/link/LinkMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/link/adapter/LinkCreateAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/link/adapter/LinkReadAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/link/adapter/LinkUpdateAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/PostMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/adapter/PostReadJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/adapter/PostSearchJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/dto/PostDetailProjection.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/dto/PostSummaryProjection.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/CommentMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/adapter/CommentReadJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/projection/CommentWithPostAndAuthorResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserSearchAdapter.java
Labels: ✨ 기능 추가, 승우 🐯, 🚢 SHIP

#462 [Docs] Logback XML 파일 추가
  module-core/src/main/resources/logback-spring.xml
Labels: ⚙️ 기타 작업, 승우 🐯

#463 [Deploy] 체크리스트, 관리자문의/답변 변경 시 이력 추가, Logback 파일 추가
  module-api/src/main/java/com/back2basics/domain/inquiry/controller/InquiryController.java
  module-api/src/main/java/com/back2basics/domain/todolist/controller/TodoListController.java
  module-core/src/main/java/com/back2basics/approval/model/ApprovalRequest.java
  module-core/src/main/java/com/back2basics/approval/port/out/ApprovalRequestCommandPort.java
  module-core/src/main/java/com/back2basics/approval/service/CreateApprovalRequestService.java
  module-core/src/main/java/com/back2basics/approval/service/UpdateApprovalResponseService.java
  module-core/src/main/java/com/back2basics/history/model/DomainType.java
  module-core/src/main/java/com/back2basics/inquiry/model/Inquiry.java
  module-core/src/main/java/com/back2basics/inquiry/port/in/UpdateInquiryUseCase.java
  module-core/src/main/java/com/back2basics/inquiry/port/out/CreateInquiryPort.java
  module-core/src/main/java/com/back2basics/inquiry/port/out/DeleteInquiryPort.java
  module-core/src/main/java/com/back2basics/inquiry/port/out/UpdateInquiryPort.java
  module-core/src/main/java/com/back2basics/inquiry/service/CreateInquiryService.java
  module-core/src/main/java/com/back2basics/inquiry/service/DeleteInquiryService.java
  module-core/src/main/java/com/back2basics/inquiry/service/UpdateInquiryService.java
  module-core/src/main/java/com/back2basics/todolist/model/TodoList.java
  module-core/src/main/java/com/back2basics/todolist/port/in/DeleteTodoListUseCase.java
  module-core/src/main/java/com/back2basics/todolist/port/in/UpdateTodoListUseCase.java
  module-core/src/main/java/com/back2basics/todolist/port/out/TodoListCommandPort.java
  module-core/src/main/java/com/back2basics/todolist/service/CreateTodoListService.java
  module-core/src/main/java/com/back2basics/todolist/service/DeleteTodoListService.java
  module-core/src/main/java/com/back2basics/todolist/service/UpdateTodoListService.java
  module-core/src/main/resources/logback-spring.xml
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/adapter/ApprovalRequestCommandAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/approval/entity/ApprovalRequestEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/adapter/CreateInquiryJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/adapter/DeleteInquiryJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/adapter/UpdateInquiryJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/todolist/adapter/TodoTodoListCommandAdapter.java
Labels: ✨ 기능 추가, ♻️ 리팩토링, 승우 🐯

#472 [Feat] 이슈테스트 전 버그 수정 및 기능 개선
  module-api/src/main/java/com/back2basics/domain/board/controller/PostController.java
  module-api/src/main/java/com/back2basics/domain/board/dto/response/PostSummaryReadResponse.java
  module-api/src/main/java/com/back2basics/domain/comment/dto/response/CommentReadResponse.java
  module-api/src/main/java/com/back2basics/domain/user/controller/UserController.java
  module-api/src/main/resources/application.yml
  module-api/src/main/resources/logback-spring.xml
  module-core/src/main/java/com/back2basics/board/file/service/FileDownloadResult.java
  module-core/src/main/java/com/back2basics/board/post/model/Post.java
  module-core/src/main/java/com/back2basics/board/post/port/in/PostSearchUseCase.java
  module-core/src/main/java/com/back2basics/board/post/service/PostSearchService.java
  module-core/src/main/java/com/back2basics/board/post/service/result/PostSummaryReadResult.java
  module-core/src/main/java/com/back2basics/comment/model/Comment.java
  module-core/src/main/java/com/back2basics/comment/service/result/CommentReadResult.java
  module-core/src/main/java/com/back2basics/infra/s3/MimeTypeUtils.java
  module-core/src/main/java/com/back2basics/user/port/in/UserSearchUseCase.java
  module-core/src/main/java/com/back2basics/user/port/out/UserSearchPort.java
  module-core/src/main/java/com/back2basics/user/service/UserSearchService.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/PostMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/adapter/PostSearchJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/board/post/dto/PostSummaryProjection.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/CommentMapper.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/adapter/CommentReadJpaAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/comment/projection/CommentReadProjection.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserSearchAdapter.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/user/repository/UserEntityRepository.java
  module-infra/src/main/java/com/back2basics/config/FileUploadConfig.java
Labels: ✨ 기능 추가, 승우 🐯

#477 [Refactor] 변수명 변경 및 response 필드 추가
  module-api/src/main/java/com/back2basics/domain/assignment/dto/response/AssignUserResponse.java
  module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectUpdateRequest.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectDetailResponse.java
  module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectGetResponse.java
  module-core/src/main/java/com/back2basics/assignment/service/result/AssignProjectListResult.java
  module-core/src/main/java/com/back2basics/assignment/service/result/AssignUserResult.java
  module-core/src/main/java/com/back2basics/project/model/Project.java
  module-core/src/main/java/com/back2basics/project/model/ProjectStatus.java
  module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
  module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectDetailResult.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectGetResult.java
  module-core/src/main/java/com/back2basics/project/service/result/ProjectListResult.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
  module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectMapper.java
Labels: ♻️ 리팩토링, 진효 🐰
